---
title: "ps_7"
author: "Charlie Olmert"
date: "11/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(fs)
library(knitr)
library(scales)
library(stringr)
```

```{r echo=FALSE}
# some of the work in cleaning up the data and downloading the data was carried over from my second midterm

# reading in the data from the csv file I have downloaded from the internet (posted on Piazza by Jack Schroeder)
results <- read_csv("mt_2_results.csv") %>% 
  # getting rid of senate and governor's races. I want to focus on what  led to polling errors in house races, which are just so much smaller and different than statewide races like Governor and Senate racesps
  filter(district != "gov",
         district != "sen") %>% 
  # concatenating state and district into one string so that districts that are the same number in different states are distinguishable from one another
  mutate(key = paste(state, district, sep = "")) %>% 
  # calculating Dem percentage lead in the vote in all of the data
  mutate(dem_adv_result = (dem_votes - rep_votes) / (rep_votes + dem_votes + other_votes))

# downloading Upshot data from the link provided for midterm 2
download.file(url = "https://goo.gl/ZRCBda", 
              destfile = "master.zip",
              quiet = TRUE,
              mode = "wb")

# unzipping the zip file
unzip("master.zip")

# saving all of the file names in order to quickly read in all of the data
file_names <- dir_ls("2018-live-poll-results-master/data/")

# reading in each file using read_csv and saving its source
polls <- map_dfr(file_names, read_csv, .id = "source")

# deleting the zipfile
file_delete("master.zip")

adj_polls <- polls %>% 
  # creating new columns to hold state, district, and wave information
  mutate(state = str_sub(source, 51, 52),
         district = str_sub(source, 53, 54),
         wave = str_sub(source, 56, 56)) %>% 
  # getting rid of senate and governor's races to match the house races I have in the results data
  filter(district != "go",
         district != "se") %>% 
  # concatenating state and district into one string, key
  mutate(key = paste(state, district, sep = "")) %>% 
  # renaming key variable so that it matches other data
  mutate(key = str_to_upper(key)) %>% 
  # organizing data to be grouped by district
  group_by(key) %>% 
  # finds total interviews in each district
  mutate(total = n()) %>% 
  ungroup()

adj_poll_res <- adj_polls %>% 
   # grouping by source and response and key and wave, which makes it so each poll sticks together and keeps the key variable around
  group_by(source, response, key, wave) %>% 
  # finds the total weight, meaning the weight given to each respondent, then adds all of those weights for each group 
  summarise(weights = sum(final_weight)) %>% 
  # reorganized data so that each response becomes a column with weights as the values below
  spread(response, weights) %>% 
  # changes NA's to zero's. Found online at: https://stackoverflow.com/questions/10139284/set-na-to-0-in-r
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>% 
  # calculating the Dem advantage in final weight
  mutate(dem_adv_poll = (Dem - Rep) / (Dem + Rep + Und + `3` + `4` + `5` + `6`))

# finding percentage of the 18-34 age group in each district. Ms. Lupion's code, which we went over in class, helped a ton for figuring out how to do this efficiently
youngest <- adj_polls %>%
  # selects relevant variables
  select(key, total, ager) %>%
  # organzes data into groups based on key. Total interviewees is included to keep that variable around for later
  group_by(key, total) %>%
  # counts number of interviewees in each age group
  count(ager) %>%
  # just selects the youngest group
  filter(ager == "18 to 34") %>%
  # finds the percentage of interviewees in the youngest age group
  mutate(yngst_per = round(100*n/total, digits = 2)) %>%
  # reorganizing and reselecting variables in the data to get rid of total variable
  ungroup() %>%
  select(key, yngst_per)

# finding percentage of the 35-49 age group in each district
younger <- adj_polls %>%
  # selects relevant variables
  select(key, total, ager) %>%
  # organzes data into groups based on key. Total interviewees is included to keep that variable around for later
  group_by(key, total) %>%
  # counts number of interviewees in each age group
  count(ager) %>%
  # just selects the younger group
  filter(ager == "35 to 49") %>%
  # finds the percentage of interviewees in the younger age group
  mutate(yngr_per = round(100*n/total, digits = 2)) %>%
  # reorganizing and reselecting variables in the data to get rid of total variable
  ungroup() %>%
  select(key, yngr_per)
  
# finding percentage of the 50-64 age group in each district
older <- adj_polls %>%
  # selects relevant variables
  select(key, total, ager) %>%
  # organzes data into groups based on key. Total interviewees is included to keep that variable around for later
  group_by(key, total) %>%
  # counts number of interviewees in each age group
  count(ager) %>%
  # just selects the older group
  filter(ager == "50 to 64") %>%
  # finds the percentage of interviewees in the older age group
  mutate(oldr_per = round(100*n/total, digits = 2)) %>%
  # reorganizing and reselecting variables in the data to get rid of total variable
  ungroup() %>%
  select(key, oldr_per)

# finding percentage of the 65+ age group in each district
oldest <- adj_polls %>%
  # selects relevant variables
  select(key, total, ager) %>%
  # organzes data into groups based on key. Total interviewees is included to keep that variable around for later
  group_by(key, total) %>%
  # counts number of interviewees in each age group
  count(ager) %>%
  # just selects the oldest group
  filter(ager == "65 and older") %>%
  # finds the percentage of interviewees in the oldest age group
  mutate(oldst_per = round(100*n/total, digits = 2)) %>%
  # reorganizing and reselecting variables in the data to get rid of total variable
  ungroup() %>%
  select(key, oldst_per)

res_adj <- results %>% 
  # renaming key variable for matching purposes
  mutate(key = str_to_upper(key)) %>% 
  # filtering out uncalled races in Mr. Schroeder's data
  filter(win_party != "UNDECIDED") %>% 
  # joining together so that only results from polled house races remain 
  inner_join(adj_poll_res, by = "key") %>% 
  # finding the difference between the resulting Democratic advantage and the polled Democratic advantage (the polling error), then multiplying and rounding that error so that it is a percentage. Then I find accuracy, which is 100 - absolute_value(error). Thus, for a district to have an accuracy of 100, that district would have 0 absolute value of error, meaning that its poll results exactly matched its actual results. I found the idea for "accuracy" in Ms. Lupion's Shiny app online -- I believe that it is a better way to visualize the error in polling.
  mutate(error = dem_adv_result - dem_adv_poll,
         error = round(100 * error, digits = 2),
         accuracy = 100 - abs(error)) %>% 
  # filtering out first wave from districts polled twice
  filter(!duplicated(key, fromLast = TRUE)) %>% 
  # selecting relevant variables
  select(key, win_party, error, accuracy) %>% 
  # joining so that age data is added for each age group
  left_join(youngest, by = "key") %>% 
  left_join(younger, by = "key") %>% 
  left_join(older, by = "key") %>% 
  left_join(oldest, by = "key")

# writing data onto a file to be used for Shiny app
write_rds(res_adj, path = "ps_7/error_data")
```

